In [51]:
import pandas as pd 
import numpy as np 

import sqlite3
from google.colab import drive
from pathlib import Path

In [ ]:
drive.mount('drive', force_remount=True)
df = pd.read_csv('drive/My Drive/MetroVan.csv')

In [53]:
Path('MetroVan.db').touch()

In [54]:
db_conn = sqlite3.connect('VancouverProperties.db')
db_cursor = db_conn.cursor()

In [ ]:
df.to_sql('VancouverPropertiesTable', db_conn, if_exists='replace', index=False)
db_vancouverproperties_init_query = pd.read_sql(''' SELECT * FROM VancouverPropertiesTable ''', db_conn)
#db_vancouverproperties_init_query.head(3)

In [56]:
data_stat = pd.read_sql(''' SELECT ZipCode, Area, Price, Beds, Address 
                                     FROM VancouverPropertiesTable
                                     WHERE Address LIKE '%Kingsway%'
                                     ORDER BY Price DESC ''', db_conn)
#data_stat.head(4)

In [74]:
data_sql = pd.read_sql(''' SELECT *
                           FROM VancouverPropertiesTable
                           WHERE Town == 'Surrey'
                           ORDER BY Price DESC ''', db_conn)
data_sql
#print(f"Average house price for sale in Richmond is : {data_stat_Avg.Avg_price_richmond[0]:,.2f} CA$")

Empty DataFrame
Columns: [Unnamed: 0, Address, Town, ZipCode, Area, Price, Beds, Baths, Broker, latitude, longitude]
Index: []